version: "3.8"

services:
  nats-server:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"

  inspector:
    image: nats-inspector
    ports:
      - 4005:80
    environment:
      - SERVER_PORT=80
      - ENV_FILE=false
